# Generated by Django 2.2.19 on 2021-03-28 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threeWeb', '0002_infomation_post_list_post_request_text_sample_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample_post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images', verbose_name='イメージ画像'),
        ),
    ]
