# Generated by Django 2.2.19 on 2021-03-28 04:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('threeWeb', '0003_sample_post_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sample_post',
            name='image',
        ),
    ]
