# Generated by Django 2.2.19 on 2021-04-01 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threeWeb', '0004_remove_sample_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='sample_post',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images', verbose_name='イメージ画像'),
        ),
    ]
